import { HttpStatus } from '@nestjs/common';

import { ErrorCode } from 'cumuco-nestjs';

export const RESERVATION_ERROR = {
  RESERVATION_NOT_FOUND: '예약을 찾을 수 없습니다.',
  RESERVATION_USER_FIND_FORBIDDEN: '본인의 예약 내역만 조회할 수 있습니다.',
  RESERVATION_USER_DELETE_FORBIDDEN: '본인의 예약 내역만 삭제할 수 있습니다.',
  RESERVATION_HOST_REFUND_FORBIDDEN: '본인의 공간에 대한 예약 내역만 환불할 수 있습니다.',
  RESERVATION_HOST_FIND_FORBIDDEN: '본인의 공간에 대한 예약 내역만 조회할 수 있습니다.',
  RESERVATION_TIME_BAD_REQUEST: '예약 시간을 다시 확인해주세요.',
  RESERVATION_COST_BAD_REQUEST: '예약 비용을 다시 확인해주세요.',
  RESERVATION_ALREADY_APPROVED: '이미 승인된 예약입니다.',
  RESERVATION_ALREADY_PAYED: '이미 결제된 예약입니다.',
  RESERVATION_SPACE_NOT_IMMEDIATE: '즉시 예약이 불가능한 공간입니다.',
};

export const RESERVATION_ERROR_CODE: ErrorCode<typeof RESERVATION_ERROR> = {
  RESERVATION_NOT_FOUND: {
    code: HttpStatus.NOT_FOUND,
    message: RESERVATION_ERROR.RESERVATION_NOT_FOUND,
  },
  RESERVATION_USER_FIND_FORBIDDEN: {
    code: HttpStatus.FORBIDDEN,
    message: RESERVATION_ERROR.RESERVATION_USER_FIND_FORBIDDEN,
  },
  RESERVATION_USER_DELETE_FORBIDDEN: {
    code: HttpStatus.FORBIDDEN,
    message: RESERVATION_ERROR.RESERVATION_USER_DELETE_FORBIDDEN,
  },
  RESERVATION_HOST_REFUND_FORBIDDEN: {
    code: HttpStatus.FORBIDDEN,
    message: RESERVATION_ERROR.RESERVATION_HOST_REFUND_FORBIDDEN,
  },
  RESERVATION_HOST_FIND_FORBIDDEN: {
    code: HttpStatus.FORBIDDEN,
    message: RESERVATION_ERROR.RESERVATION_HOST_FIND_FORBIDDEN,
  },
  RESERVATION_TIME_BAD_REQUEST: {
    code: HttpStatus.BAD_REQUEST,
    message: RESERVATION_ERROR.RESERVATION_TIME_BAD_REQUEST,
  },
  RESERVATION_COST_BAD_REQUEST: {
    code: HttpStatus.BAD_REQUEST,
    message: RESERVATION_ERROR.RESERVATION_COST_BAD_REQUEST,
  },
  RESERVATION_ALREADY_APPROVED: {
    code: HttpStatus.CONFLICT,
    message: RESERVATION_ERROR.RESERVATION_ALREADY_APPROVED,
  },
  RESERVATION_ALREADY_PAYED: {
    code: HttpStatus.CONFLICT,
    message: RESERVATION_ERROR.RESERVATION_ALREADY_PAYED,
  },
  RESERVATION_SPACE_NOT_IMMEDIATE: {
    code: HttpStatus.CONFLICT,
    message: RESERVATION_ERROR.RESERVATION_SPACE_NOT_IMMEDIATE,
  },
};
