version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run config:dev
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  name: rooflupin-build-$(date +%Y-%m-%d)
cache:
  paths:
    - 'node_modules/**/*'
