version: '3.5'
services:
  database_master:
    image: mysql:8.0.30
    container_name: 'database_master'
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./docker/db/master/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=RoofS3cret
      - MYSQL_USER=roof_user
      - MYSQL_DATABASE=roof
      - MYSQL_PASSWORD=RoofS3cret
    networks:
      - mynetwork
  database_slave:
    image: mysql:8.0.30
    container_name: 'database_slave'
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3307:3306
    volumes:
      - mysqldata_slave:/var/lib/mysql
      - ./docker/db/slave/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=RoofS3cret
      - MYSQL_USER=roof_user
      - MYSQL_DATABASE=roof
      - MYSQL_PASSWORD=RoofS3cret
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysqldata_master:
  mysqldata_slave:
