export const GUEST_TERMS = {
  PRIVATE_USAGE: 'GUEST_TERMS_PRIVATE_USAGE',
  OPERATION: 'GUEST_TERMS_OPERATION',
  USAGE: 'GUEST_TERMS_USAGE',
  LOCATION: 'GUEST_TERMS_LOCATION',
  PRIVATE_ESSENTIAL: 'GUEST_TERMS_PRIVATE_ESSENTIAL',
  PRIVATE_OPTIONAL: 'GUEST_TERMS_PRIVATE_OPTIONAL',
} as const;

export const GUEST_TERMS_KOR: Record<(typeof GUEST_TERMS)[keyof typeof GUEST_TERMS], string> = {
  GUEST_TERMS_PRIVATE_USAGE: '개인정보 처리 방침',
  GUEST_TERMS_OPERATION: '루프루팡 운영정책',
  GUEST_TERMS_USAGE: '루프루팡 이용약관',
  GUEST_TERMS_LOCATION: '위치기반 서비스 이용약관',
  GUEST_TERMS_PRIVATE_ESSENTIAL: '게스트 개인정보 수집 및 이용(필수)',
  GUEST_TERMS_PRIVATE_OPTIONAL: '게스트 개인정보 수집 및 이용(선택)',
} as const;

export const HOST_TERMS = {
  PRIVATE_USAGE: 'HOST_TERMS_PRIVATE_USAGE',
  USAGE: 'HOST_TERMS_USAGE',
  SETTLEMENT_REFUND: 'HOST_TERMS_SETTLEMENT_REFUND',
  LOCATION_MANAGEMENT: 'HOST_TERMS_LOCATION_MANAGEMENT',
  ADVERTISEMENT: 'HOST_TERMS_ADVERTISEMENT',
  PRIVATE_ESSENTIAL: 'HOST_TERMS_PRIVATE_ESSENTIAL',
} as const;

export const HOST_TERMS_KOR: Record<(typeof HOST_TERMS)[keyof typeof HOST_TERMS], string> = {
  HOST_TERMS_PRIVATE_USAGE: '호스트 개인정보 처리 방침',
  HOST_TERMS_USAGE: '호스트 이용약관',
  HOST_TERMS_SETTLEMENT_REFUND: '정산 및 환불 정책',
  HOST_TERMS_LOCATION_MANAGEMENT: '루프루팡 공간관리 정책',
  HOST_TERMS_ADVERTISEMENT: '루프루팡 광고채널 이용약관',
  HOST_TERMS_PRIVATE_ESSENTIAL: '호스트 개인정보 동의(필수)',
} as const;
