export const GUEST_TERMS = {
  PRIVATE_USAGE: 'GUEST_TERMS_PRIVATE_USAGE',
  OPERATION: 'GUEST_TERMS_OPERATION',
  USAGE: 'GUEST_TERMS_USAGE',
  LOCATION: 'GUEST_TERMS_LOCATION',
  PRIVATE_ESSENTIAL: 'GUEST_TERMS_PRIVATE_ESSENTIAL',
  PRIVATE_OPTIONAL: 'GUEST_TERMS_PRIVATE_OPTIONAL',
} as const;

export const HOST_TERMS = {
  PRIVATE_USAGE: 'HOST_TERMS_PRIVATE_USAGE',
  USAGE: 'HOST_TERMS_USAGE',
  SETTLEMENT_REFUND: 'HOST_TERMS_SETTLEMENT_REFUND',
  LOCATION_MANAGEMENT: 'HOST_TERMS_LOCATION_MANAGEMENT',
  ADVERTISEMENT: 'HOST_TERMS_ADVERTISEMENT',
  PRIVATE_ESSENTIAL: 'HOST_TERMS_PRIVATE_ESSENTIAL',
} as const;
